[project]
name = "ai-ros"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pytest-asyncio>=1.3.0",
    "ruff>=0.14.10",
    "sentence-transformers>=5.2.0",
]
